// Alias dictionaries for deterministic skill normalization.
//
// Keys are lowercase, pre-normalized forms (punctuation-stripped, single-
// spaced) as produced by `skills-normalizer.normalizeSkill`. Values are the
// canonical lowercase form the rest of the system stores and compares.
//
// Invariants (covered by tests):
//   - every key is lowercase
//   - every value is lowercase
//   - no key appears in more than one category map
//   - SKILL_ALIASES count equals the sum of all category map counts

export const LANGUAGE_ALIASES: Readonly<Record<string, string>> = {
  js: "javascript",
  "java script": "javascript",
  "java-script": "javascript",
  ecmascript: "javascript",
  ts: "typescript",
  "type script": "typescript",
  "type-script": "typescript",
  py: "python",
  py3: "python",
  python3: "python",
  golang: "go",
  cpp: "c++",
  "c-plus-plus": "c++",
  "c plus plus": "c++",
  csharp: "c#",
  "c-sharp": "c#",
  "c sharp": "c#",
  rb: "ruby",
  rs: "rust",
  kt: "kotlin",
  "obj-c": "objective-c",
  objc: "objective-c",
  "objective c": "objective-c",
};

export const FRONTEND_ALIASES: Readonly<Record<string, string>> = {
  "react.js": "react",
  reactjs: "react",
  "react js": "react",
  "react-js": "react",
  "vue.js": "vue",
  vuejs: "vue",
  "vue js": "vue",
  "vue-js": "vue",
  "vue 3": "vue",
  "angular.js": "angular",
  angularjs: "angular",
  "angular js": "angular",
  "angular-js": "angular",
  "next.js": "next",
  nextjs: "next",
  "next js": "next",
  "nuxt.js": "nuxt",
  nuxtjs: "nuxt",
  "svelte.js": "svelte",
  sveltejs: "svelte",
  "solid.js": "solid",
  solidjs: "solid",
  "remix.js": "remix",
  "astro.js": "astro",
  "ember.js": "ember",
  emberjs: "ember",
};

export const BACKEND_ALIASES: Readonly<Record<string, string>> = {
  "node.js": "node",
  nodejs: "node",
  "node js": "node",
  "node-js": "node",
  "express.js": "express",
  expressjs: "express",
  "express js": "express",
  "nest.js": "nest",
  nestjs: "nest",
  "nest js": "nest",
  "fastify.js": "fastify",
  "koa.js": "koa",
  koajs: "koa",
  "hapi.js": "hapi",
  hapijs: "hapi",
  "spring boot": "spring",
  "spring-boot": "spring",
  springboot: "spring",
  "ruby on rails": "rails",
  "ruby-on-rails": "rails",
  "ror": "rails",
  "asp net": "asp.net",
  "asp-net": "asp.net",
  "asp.net core": "asp.net",
  dotnet: ".net",
  "dot net": ".net",
  "dot-net": ".net",
  "net core": ".net",
  "laravel php": "laravel",
  "django rest": "django",
  "flask py": "flask",
};

export const DATABASE_ALIASES: Readonly<Record<string, string>> = {
  mongo: "mongodb",
  "mongo db": "mongodb",
  "mongo-db": "mongodb",
  postgres: "postgresql",
  postgre: "postgresql",
  pg: "postgresql",
  "my sql": "mysql",
  "my-sql": "mysql",
  "ms sql": "mssql",
  "ms-sql": "mssql",
  "microsoft sql server": "mssql",
  "sql server": "mssql",
  "sql-server": "mssql",
  "elastic search": "elasticsearch",
  "elastic-search": "elasticsearch",
  elastic: "elasticsearch",
  dynamo: "dynamodb",
  "dynamo db": "dynamodb",
  "dynamo-db": "dynamodb",
  "cloud firestore": "firestore",
  "google firestore": "firestore",
  "redis db": "redis",
  sqlite3: "sqlite",
  "sql-lite": "sqlite",
};

export const CLOUD_ALIASES: Readonly<Record<string, string>> = {
  "amazon web services": "aws",
  "amazon-web-services": "aws",
  "amazon aws": "aws",
  "aws cloud": "aws",
  gcp: "google-cloud-platform",
  "google cloud": "google-cloud-platform",
  "google-cloud": "google-cloud-platform",
  "google cloud platform": "google-cloud-platform",
  "microsoft azure": "azure",
  "microsoft-azure": "azure",
  "ms azure": "azure",
  "ms-azure": "azure",
  "windows azure": "azure",
  "azure cloud": "azure",
  "digital ocean": "digitalocean",
  "digital-ocean": "digitalocean",
  "alibaba cloud": "alibaba-cloud",
  "tencent cloud": "tencent-cloud",
  "ibm cloud": "ibm-cloud",
  "oracle cloud": "oracle-cloud",
};

export const DEVOPS_ALIASES: Readonly<Record<string, string>> = {
  k8s: "kubernetes",
  kube: "kubernetes",
  "github actions": "github-actions",
  "gh actions": "github-actions",
  gha: "github-actions",
  "gitlab ci": "gitlab-ci",
  "gitlab-ci/cd": "gitlab-ci",
  "circle ci": "circleci",
  "circle-ci": "circleci",
  travis: "travis-ci",
  "travis ci": "travis-ci",
  "jenkins pipeline": "jenkins",
  "ci cd": "ci-cd",
  "ci/cd": "ci-cd",
  "continuous integration": "ci-cd",
  "continuous delivery": "ci-cd",
  "continuous deployment": "ci-cd",
  iac: "infrastructure-as-code",
  "infrastructure as code": "infrastructure-as-code",
  "docker compose": "docker-compose",
  dockercompose: "docker-compose",
  "helm charts": "helm",
};

export const TOOLING_ALIASES: Readonly<Record<string, string>> = {
  "tailwind css": "tailwind",
  tailwindcss: "tailwind",
  "tailwind-css": "tailwind",
  "material ui": "mui",
  "material-ui": "mui",
  "material design": "mui",
  "styled components": "styled-components",
  "styled-component": "styled-components",
  "shadcn ui": "shadcn",
  "shadcn-ui": "shadcn",
  "shadcn/ui": "shadcn",
  "chakra ui": "chakra",
  "chakra-ui": "chakra",
  "radix ui": "radix",
  "radix-ui": "radix",
  "ant design": "antd",
  "ant-design": "antd",
  antdesign: "antd",
  "web pack": "webpack",
  "es build": "esbuild",
  "es-build": "esbuild",
};

export const TESTING_ALIASES: Readonly<Record<string, string>> = {
  "react testing library": "rtl",
  "react-testing-library": "rtl",
  "junit 5": "junit",
  junit5: "junit",
  "py test": "pytest",
  "py-test": "pytest",
  "mocha.js": "mocha",
  mochajs: "mocha",
  "chai.js": "chai",
  chaijs: "chai",
  "cypress io": "cypress",
  "cypress-io": "cypress",
  "cypress.io": "cypress",
  "play wright": "playwright",
  "play-wright": "playwright",
  "selenium webdriver": "selenium",
  "selenium-webdriver": "selenium",
  "r spec": "rspec",
  "r-spec": "rspec",
  qa: "quality-assurance",
  "quality assurance": "quality-assurance",
  "end-to-end testing": "e2e",
  "end to end testing": "e2e",
  "end to end": "e2e",
  "unit testing": "unit-tests",
  "integration testing": "integration-tests",
};

export const AI_ML_ALIASES: Readonly<Record<string, string>> = {
  "large language model": "llm",
  "large-language-model": "llm",
  "large language models": "llm",
  llms: "llm",
  "retrieval augmented generation": "rag",
  "retrieval-augmented-generation": "rag",
  chatgpt: "gpt",
  "chat-gpt": "gpt",
  "openai api": "openai",
  "openai-api": "openai",
  "gemini api": "gemini",
  "gemini-api": "gemini",
  "claude api": "claude",
  "claude-api": "claude",
  "hugging face": "huggingface",
  "hugging-face": "huggingface",
  "py torch": "pytorch",
  "py-torch": "pytorch",
  "tensor flow": "tensorflow",
  "tensor-flow": "tensorflow",
  tf: "tensorflow",
  sklearn: "scikit-learn",
  "scikit learn": "scikit-learn",
  np: "numpy",
  "open cv": "opencv",
  "open-cv": "opencv",
  "vector db": "vector-database",
  vectordb: "vector-database",
  "pine cone": "pinecone",
  "pine-cone": "pinecone",
  ml: "machine-learning",
  // The abbreviation mapped but the written-out form did not, so a job asking
  // for "machine learning" never matched a CV listing "ML".
  "machine learning": "machine-learning",
  nlp: "natural-language-processing",
  "natural language processing": "natural-language-processing",
};

export const MOBILE_ALIASES: Readonly<Record<string, string>> = {
  "react native": "react-native",
  reactnative: "react-native",
  rn: "react-native",
  "flutter dart": "flutter",
  "jetpack compose": "jetpack-compose",
  "swift ui": "swiftui",
  "swift-ui": "swiftui",
  "kotlin multiplatform": "kotlin-multiplatform",
  "kotlin multi platform": "kotlin-multiplatform",
  kmm: "kotlin-multiplatform",
  kmp: "kotlin-multiplatform",
  "ios development": "ios",
  "ios app": "ios",
  "iphone app": "ios",
  "android development": "android",
  "android app": "android",
  "android studio": "android",
  "ionic framework": "ionic",
  "xamarin forms": "xamarin",
  "apache cordova": "cordova",
  "apache-cordova": "cordova",
};

export const CONCEPT_ALIASES: Readonly<Record<string, string>> = {
  restful: "rest",
  "restful api": "rest",
  "restful-api": "rest",
  "rest api": "rest",
  "rest-api": "rest",
  "graphql api": "graphql",
  "graphql-api": "graphql",
  gql: "graphql",
  "web sockets": "websocket",
  "web-sockets": "websocket",
  websockets: "websocket",
  ws: "websocket",
  "oauth 2": "oauth2",
  "oauth-2": "oauth2",
  "oauth 2.0": "oauth2",
  "oauth-2.0": "oauth2",
  "jwt tokens": "jwt",
  "json web token": "jwt",
  "json-web-token": "jwt",
  sso: "single-sign-on",
  "single sign on": "single-sign-on",
  tdd: "test-driven-development",
  bdd: "behavior-driven-development",
  ddd: "domain-driven-design",
  "event driven": "event-driven",
  "mono repo": "monorepo",
  "micro services": "microservices",
  "micro-services": "microservices",
  "server less": "serverless",
  "server-less": "serverless",
};

// Security and networking were absent from the dictionary entirely: a grep for
// security, cyber, threat, network, tcp, wireshark or siem returned nothing, so
// every skill in those domains fell through as an opaque raw string.
export const SECURITY_ALIASES: Readonly<Record<string, string>> = {
  "cyber security": "cybersecurity",
  "cyber-security": "cybersecurity",
  "information security": "information-security",
  infosec: "information-security",
  appsec: "application-security",
  "application security": "application-security",
  "cloud security": "cloud-security",
  "threat detection": "threat-detection",
  "threat hunting": "threat-hunting",
  "threat intelligence": "threat-intelligence",
  "security investigation": "security-investigation",
  "security investigations": "security-investigation",
  "incident response": "incident-response",
  "security operations": "soc",
  "security operations center": "soc",
  "identity threat detection and response": "identity-threat-detection-and-response",
  itdr: "identity-threat-detection-and-response",
  edr: "endpoint-detection-and-response",
  "endpoint detection and response": "endpoint-detection-and-response",
  "mitre attack": "mitre-attack",
  "mitre att&ck": "mitre-attack",
  "penetration testing": "penetration-testing",
  pentest: "penetration-testing",
  pentesting: "penetration-testing",
  "ethical hacking": "penetration-testing",
  "reverse engineering": "reverse-engineering",
  "malware analysis": "malware-analysis",
  "digital forensics": "forensics",
  "windows forensics": "windows-forensics",
  "cloud forensics": "cloud-forensics",
  "detection engineering": "detection-engineering",
  "detection authoring": "detection-engineering",
  "attacker tradecraft": "adversary-tradecraft",
  "adversary tradecraft": "adversary-tradecraft",
  "attacker landscape": "adversary-tradecraft",
  "kill chain": "kill-chain",
  "attacker kill chain": "kill-chain",
  "cyber attack": "cyber-attack",
  "cyber attacks": "cyber-attack",
  "cyber-attacks": "cyber-attack",
  "identity based attacks": "identity-based-attacks",
  "identity-based attacks": "identity-based-attacks",
  "identity protection": "identity-protection",
  "hybrid identity": "hybrid-identity",
  "active directory": "active-directory",
  "windows internals": "windows-internals",
  "vulnerability assessment": "vulnerability-assessment",
  "vulnerability management": "vulnerability-management",
  "security research": "security-research",
  "security researcher": "security-research",
  "zero trust": "zero-trust",
  "security copilot": "security-copilot",
  "enterprise security": "enterprise-security",
};

export const NETWORKING_ALIASES: Readonly<Record<string, string>> = {
  "tcp/ip": "tcp-ip",
  "tcp ip": "tcp-ip",
  tcpip: "tcp-ip",
  "computer networks": "networking",
  "computer networking": "networking",
  "network protocols": "networking",
  "networking protocols": "networking",
  "network security": "network-security",
  "packet analysis": "packet-analysis",
  "packet capture": "packet-analysis",
  pcap: "packet-analysis",
  "traffic analysis": "network-traffic-analysis",
  "network traffic analysis": "network-traffic-analysis",
  "wire shark": "wireshark",
  tshark: "wireshark",
  firewalls: "firewall",
  "osi model": "osi-model",
  "load balancing": "load-balancing",
};

/**
 * Fragments where `/` is part of one concept rather than a separator between
 * two. Applied before compound splitting, so `tcp/ip` survives while `html/css`
 * and `aws/gcp` are correctly split into two skills.
 */
export const SLASH_COMPOUNDS: Readonly<Record<string, string>> = {
  "tcp/ip": "tcp-ip",
  "ci/cd": "ci-cd",
  "a/b": "a-b",
  "i/o": "i-o",
  "s/mime": "s-mime",
  "udp/ip": "udp-ip",
};

export const SKILL_ALIASES: Readonly<Record<string, string>> = {
  ...LANGUAGE_ALIASES,
  ...FRONTEND_ALIASES,
  ...BACKEND_ALIASES,
  ...DATABASE_ALIASES,
  ...CLOUD_ALIASES,
  ...DEVOPS_ALIASES,
  ...TOOLING_ALIASES,
  ...TESTING_ALIASES,
  ...AI_ML_ALIASES,
  ...MOBILE_ALIASES,
  ...CONCEPT_ALIASES,
  ...SECURITY_ALIASES,
  ...NETWORKING_ALIASES,
};
