/**
 * Shared TypeScript contracts for the Role 4 AI service.
 *
 * Produced by: Role 4 (AI service).
 * Consumed by: Role 4 internal code, Role 3 (Backend Lead) controllers.
 * Types are plain data — no runtime dependencies.
 *
 * Re-exports `ProfileInput` and `JobAnalysis` from the matching layer so
 * that consumers of the AI service do not need to import from two files.
 */

export type { ProfileInput, JobAnalysis } from "../matching/matching.types";

/**
 * Result of AI profile analysis.
 * Produced by `analyzeProfile`; persisted by the Backend on the user document.
 */
export interface ProfileAnalysis {
  seniorityEstimate: "junior" | "mid" | "senior";
  strengths: string[];
  weaknesses: string[];
  suggestedRoles: string[];
  summary: string;
}

/**
 * Which kind of interview simulation the user is running.
 */
export type InterviewType = "hr" | "technical";

/**
 * A single interview question returned by `generateInterviewQuestions`.
 * `id` is stable and generated by Role 4 (e.g. "q1", "q2", ...).
 */
export interface InterviewQuestion {
  id: string;
  question: string;
  topic: string;
  expectedFocus: string;
}

/**
 * Input for generating a batch of interview questions.
 * Consumed by `generateInterviewQuestions`.
 */
export interface GenerateQuestionsInput {
  readonly interviewType: InterviewType;
  readonly profileSkills: string[];
  readonly jobRequiredSkills?: string[];
  readonly count: number;
  readonly language?: "en" | "he";
}

/**
 * AI evaluation of a single user answer.
 * Produced by `evaluateAnswer`; numeric scores are clamped to 0–100
 * inside `ai.service.ts` before being returned.
 */
export interface AnswerEvaluation {
  score: number;
  clarity: number;
  correctness: number;
  depth: number;
  feedback: string;
  improvementTips: string[];
}

/**
 * Input for scoring a single answer.
 * Consumed by `evaluateAnswer`.
 */
export interface EvaluateAnswerInput {
  readonly question: string;
  readonly expectedFocus: string;
  readonly userAnswer: string;
  readonly interviewType: InterviewType;
}

/**
 * Parsed shape of the AI's semantic-match response.
 * The AI contributes only a semantic sub-score; the final match score
 * is computed deterministically in `matching.service.ts`.
 */
export interface SemanticMatchAiResponse {
  aiSemanticScore: number;
  explanation: string;
}
